[serve]
port = 8085

[[proxy]]
# Use the protocol path for flights API
backend = "http://localhost:3001/api/v1/flights"
rewrite = "/api/v1/flights"

[build]
target = "index.html"
dist = "dist"
public_url = "."
