[package]
name = "sky-tracer-demo"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/airport-anywhere",
    "crates/flight-controller", "crates/flightmare-tracker",
    "crates/sky-tracer",
]

[dependencies]
sky-tracer = { path = "crates/sky-tracer" }
airport-anywhere = { path = "crates/airport-anywhere" }
flight-controller = { path = "crates/flight-controller" }
