export PORT := "9093"
export AIRPORT_SERVICE_URL := "http://localhost:3000/api"
export FLIGHT_SERVICE_URL := "http://localhost:3001/api"
export SATELLITE_SERVICE_URL := "http://localhost:3002/api"
export RUST_LOG := "info,tower_http=debug,sky_nexus=debug"

default:
    @just --list

run:
    cargo run
