export PORT := "9093"
export SATELLITE_SERVICE_URL := "http://localhost:3002/api"
export AIRPORT_SERVICE_URL := "http://localhost:3000"
export FLIGHT_SERVICE_URL := "http://localhost:3003/api/v1/flights"
export RUST_LOG := "info,tower_http=debug,sky_nexus=debug"

default:
    @just --list

run:
    cargo run
