export PORT := "9093"
export SERVICE_NAME := "sky-nexus"
export RUST_LOG := "info,tower_http=debug,sky_nexus=debug,rmcp=debug"
export AIRPORT_SERVICE_BASE_URL := "http://localhost:3000"
export FLIGHT_SERVICE_BASE_URL := "http://localhost:3001"
export SATELLITE_SERVICE_BASE_URL := "http://localhost:3002"
export BABEL_SERVICE_BASE_URL := "http://localhost:3003"

default:
    @just --list

run:
    echo "Running sky-nexus service..."
    cargo run
