[package]
name = "sky-tracer"
version = "0.1.0"
edition = "2021"

[features]
default = ["protocol"]
protocol = ["utoipa"]

[dependencies]
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
serde_json = "1.0"
utoipa = { version = "5.3", optional = true }
